
export const SAVE_USER_REQUEST = 'SAVE_USER_REQUEST';
export const SAVE_USER_RECEIVED = 'SAVE_USER_RECEIVED';

export const USERS_DATA_INIT = 'USERS_DATA_INIT';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_RECEIVED = 'DELETE_USER_RECEIVED';

export const UPDATE_USER_REQUEST = 'UDATE_USER_REQUEST';
export const UPDATE_USER_RECEIVED = 'UPDATE_USER_RECEIVED';

export const SAVE_TODO_REQUEST = 'SAVE_TODO_REQUEST';
export const SAVE_TODO_RECEIVED = 'SAVE_TODO_RECEIVED';

export const TODO_DATA_INIT = 'TODO_DATA_INIT';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_RECEIVED = 'DELETE_TODO_RECEIVED';
